#!/usr/bin/zsh
# author: combofish
# email: combofish49@gmail.com
# description: shell script for config system.


config_python_envs(){
    # conda create -n test-py36 python=3.6

    # exec next line fail
    # conda activate test-py36

    conda install tensorflow=1.15 pillow
}

config_python_envs_cv(){
    # conda create -n test-py36-cv python=3.6
    # conda activate test-py36-cv
    conda install opencv
}

script(){
    echo ">>> script..."
    # config_python_envs
    config_python_envs_cv
}

script
